config/routes.rb
Rails.application.routes.draw do
  #mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root "results#index"

  resources :results, only: [:index, :new, :create, :show, :destroy] do
    collection do
      get 'search'
    end
  end

  resources :works,　only: [:new, :create]
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    # user ||= User.new # guest user (not logged in)
    # if user.admin?
    #   can :manage, :all
    # else
    #   can [:read, :create, :destroy], :all
    # end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :user
  belongs_to :work

  def self.search(search)
    search_time = "#{search[:year]}-#{search[:month]}-01"
    Result.where(user_id: "#{search[:user_id]}").where(created_at: search_time.in_time_zone.all_month)
    
    #if search[:month].to_i >= 10
    #  Result.where(user_id: "#{search[:user_id]}").where('created_at: LIKE(?)', "#{search[:year].to_i}-#{search[:month].to_i}-%" )
    #else
    #  Result.where(user_id: "#{search[:user_id]}").where('created_at: LIKE(?)', "#{search[:year].to_i}-0#{search[:month].to_i}-%" )
    #end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, uniqueness: true
  has_many :results
end

app/models/work.rb
class Work < ApplicationRecord
  has_many :results
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  

  def index
  end

  def new
    @result = Result.new
    @results = Result.where(user_id: current_user.id)
    @works = Work.all
  end

  def create
    @result = Result.new(result_params)
    if params[:result][:qty] == ""
      redirect_to new_result_path,alert: "数の入力がありません"
    elsif @result.save
      render :create
    else
      redirect_to new_result_path,alert: "契約の入力がありません"
    end
  end

  def show
    if current_user.admin?
      @result = Result.all
    else
      redirect_to root_path, alert: "確認の権限がありません"
    end
  end

  def search
    @results = Result.search(params)
    amounts = 0
    @results.each do |result|
      amounts += result.work.price * result.qty
    end
    @bill = amounts
  end

  def destroy
    result = Result.find(params[:id])
    result.destroy
    redirect_to root_path, notice: "契約を削除しました"
  end

  private

  def result_params
    params.require(:result).permit(:work_id,:qty).merge(user_id: current_user.id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/controllers/works_controller.rb
class WorksController < ApplicationController

  def new
    if current_user.admin?
      @work = Work.new
      @works = Work.all
    else
      redirect_to root_path, alert: "業務登録の権限がありません"
    end
  end

  def create
    @work = Work.new(work_params)
    if params[:work][:price] == ""
      redirect_to new_work_path,alert: "金額の入力がありません"
    elsif params[:work][:name] == ""
      redirect_to new_work_path,alert: "契約の入力がありません"
    else
      @work.save
    end
  end

  #def destroy
  #  work = Work.find(params[:id])
  #  work.destroy
  #  redirect_to root_path, notice: "削除しました"
  #end

  private
  def work_params
    params.require(:work).permit(:name, :price)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_notifications.html.haml
.Notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  .Wrapper
    %head
      %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
      %title InvoiceBoard2
      = csrf_meta_tags
      = csp_meta_tag
      = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
      = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    %body
      = render 'layouts/notifications'
      = yield

    %footer
      = " Copyright Yamato 2020"

app/views/results/create.html.haml
.Result__create
  .Result__create__comment
    送信完了しましたん
  .Result__create__btn
    = link_to "戻る","/results",class: 'Button--logout'

app/views/results/index.html.haml
.Main
  .Main__title
    業務選択
  .Main__selects
    .Main__selects__check
      = link_to "登録", '/results/new', class: 'Button--main'
    .Main__selects__check
      = link_to "確認(管理者のみ）", '/results/:id', class: 'Button--main'
    .Main__selects__check
      = link_to "業務登録（管理者のみ）", '/works/new', class: 'Button--main'

  .Main__logout
    = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'Button--logout'

app/views/results/new.html.haml
.Register
  .Register__form
    = form_with model: @result, local: true do |f|
      = f.label "契約種類" 
      = f.collection_select(:work_id, Work.all, :id, :name, {prompt: true}, {class:"Register__form__box"})

      = f.label "件数" 
      = f.number_field :qty, min: 0,class:"Register__form__box"

      = f.submit '登録', class: 'Button--login'

  .Register__show
    - @results.each do |result|
      .Register__show__contents
        .Register__show__contents__qty
          = "#{result.work.name}   #{result.qty}件     #{result.created_at.strftime('%Y/%m/%d')}"
        .Register__show__contents__derete
          = link_to '削除', "/results/#{result.id}", method: :delete, class:"Button"

app/views/results/search.html.haml
.Search
  .Search__title
    検索結果
  .Search__display
    - if @results.present?
      = "#{@results[0].user.name}さんの請求額は"
      %span.Search__display__bill #{@bill}
      %span 円です
    - else
      = "請求額はありません"
  .Search__btn
    = link_to "戻る","/results", class: 'Button--logout'

app/views/results/show.html.haml
.Show
  .Show__title
    実績確認
  = form_with url: search_results_path, local: true, method: :get, class: "Show__form" do |f|
    = f.label "ユーザーID"
    = f.number_field :user_id, min: 1, max: 30

    = f.label "年"
    = f.number_field :year, min: 2020, max: 2050

    = f.label "月"
    = f.number_field :month, min: 01, max: 12

    = f.submit "検索", class: "Button--login"

app/views/users/edit.html.haml
.AccountPage
  .AccountPage__title
    %h2 Edit Account
    %h5 アカウントの編集
    = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'Button'
    = link_to "トップページに戻る", :back, class: 'Button'
  .AccountPage__form
    = form_for(current_user) do |f|
      .FormField
        .FormField__label--normal
          = f.label :name
        .FormField__input--normal
          = f.text_field :name, autofocus: true
      .FormField
        .FormField__label--normal
          = f.label :email
        .FormField__input--normal
          = f.email_field :email
      = f.submit "Update", class: 'Button UserButton'

app/views/works/create.html.haml
.WorkCreate
  .WorkCreate__title
    登録完了しましたん
  .WorkCreate__btn
    = link_to "戻る","/results"

app/views/works/new.html.haml
.Work
  .Work__title
    業務内容登録
  .Work__form
    = form_with model: @work , local: true do |f|
      = f.label "契約名称"
      = f.text_field :name

      = f.label "契約単価"
      = f.number_field :price

      = f.submit "登録",class: "Button--login"

  .Work__show
    - @works.each do |work|
      .Work__show__contents
        .Work__show__contents__qty
          = "#{work.name}   #{work.price}円"
        -# .Work__show__contents__derete
          -# = link_to '削除', "/works/#{work.id}", method: :delete